//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
		///<summary>
		///constructor de la clase 
		///</summary>
        public Actividad()
        {
            this.Actividad_Ejercicio = new HashSet<Actividad_Ejercicio>();
            this.Programa_Actividad = new HashSet<Programa_Actividad>();
        }
    
		///<summary>
		///ID de la actividad
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///Nombre de la actividad
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///Tipo de la actividad
		///</summary>
        public string Tipo { get; set; }
    
		///<summary>
		///Coleccion de relaciones con ejercicios
		///</summary>
        public virtual ICollection<Actividad_Ejercicio> Actividad_Ejercicio { get; set; }
		
		///<summary>
		///Colleccion de relaciones con programas 
		///</summary>
        public virtual ICollection<Programa_Actividad> Programa_Actividad { get; set; }
    }
}
