//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergia
    {
		///<summary>
		///constructor de la clase 
		///</summary>
        public Alergia()
        {
            this.Alumno_Alergia = new HashSet<Alumno_Alergia>();
        }
		
		///<summary>
		///ID de la alergia
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///Nombre de la alergia
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///Descripcion de la alergia
		///</summary>
        public string Descripcion { get; set; }
		
		///<summary>
		///Tratamiento de la alergia
		///</summary>
        public string Tratamiento { get; set; }
    
		///<summary>
		///relaciones con alumnos de la alergia
		///</summary>
        public virtual ICollection<Alumno_Alergia> Alumno_Alergia { get; set; }
    }
}
