//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
		///<summary>
		///constructor de la clase 
		///</summary>
        public Alumno()
        {
            this.Alumno_Alergia = new HashSet<Alumno_Alergia>();
            this.Alumno_Medicamento = new HashSet<Alumno_Medicamento>();
            this.Grupo_Alumno = new HashSet<Grupo_Alumno>();
        }
    
		///<summary>
		///ID del alumno
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///Nombre del alumno
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///Direccion del alumno
		///</summary>
        public string Direccion { get; set; }
		
		///<summary>
		///ID del tutor relacionado
		///</summary>
        public int IdTutor { get; set; }
		
		///<summary>
		///Fecha de nacimiento del alumno
		///</summary>
        public System.DateTime FechaNacimiento { get; set; }
		
		///<summary>
		///fecha de registro del alumno
		///</summary>
        public System.DateTime FechaRegistro { get; set; }
		
		///<summary>
		///CURP del alumno ***
		///</summary>
        public string CURP { get; set; }
		
		///<summary>
		///Grado academico del alumno
		///</summary>
        public string GradoAcademico { get; set; }
		
		///<summary>
		///Talla del uniforme 
		///</summary>
        public string TallaUniforme { get; set; }
		
		///<summary>
		///id del diagnostico al que se relaciona
		///</summary>
        public Nullable<int> IdDiagnostico { get; set; }
		
		///<summary>
		///id del grupo al que pertenece
		///</summary>
        public Nullable<int> IdGrupo { get; set; }
		
		///<summary>
		///id de la rutina a la que pertenece
		///</summary>
        public Nullable<int> IdRutina { get; set; }
    
		///<summary>
		///coleccion de alergias del alumno
		///</summary>
        public virtual ICollection<Alumno_Alergia> Alumno_Alergia { get; set; }
		
		///<summary>
		///Tutor del alumno
		///</summary>
        public virtual Tutor Tutor { get; set; }
		
		///<summary>
		///diagnostico del alumno
		///</summary>
        public virtual Diagnostico Diagnostico { get; set; }
		
		///<summary>
		///grupo al que pertenece
		///</summary>
        public virtual Grupo Grupo { get; set; }
		
		///<summary>
		///rutina relacionada con el alumno
		///</summary>
        public virtual Rutina Rutina { get; set; }
		
		///<summary>
		///coleccion de medicamentos del alumno
		///</summary>
        public virtual ICollection<Alumno_Medicamento> Alumno_Medicamento { get; set; }
		
		///<summary>
		///coleccion de alumnos que pertenecen al mismo grupo
		///</summary>
        public virtual ICollection<Grupo_Alumno> Grupo_Alumno { get; set; }
    }
}
