//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno_Alergia
    {
        public int ID { get; set; }
        public int IdAlumno { get; set; }
        public int IdAlergia { get; set; }
    
        public virtual Alergia Alergia { get; set; }
        public virtual Alumno Alumno { get; set; }
    }
}
