//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
		///<summary>
		///cosntructor de la clase 
		///</summary>
        public Diagnostico()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Diagnostico_Discapacidad = new HashSet<Diagnostico_Discapacidad>();
        }
    
		///<summary>
		///id del diagnostico
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del diagnostico
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///descripcion del diagnostico
		///</summary>
        public string Descripcion { get; set; }
    
		///<summary>
		///coleccion de alumnos con el mismo diagnostico
		///</summary>
        public virtual ICollection<Alumno> Alumno { get; set; }
		
		///<summary>
		///coleccion de relaciones con discapacidades-
		///</summary>
        public virtual ICollection<Diagnostico_Discapacidad> Diagnostico_Discapacidad { get; set; }
    }
}
