//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public Diagnostico()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Diagnostico_Discapacidad = new HashSet<Diagnostico_Discapacidad>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Diagnostico_Discapacidad> Diagnostico_Discapacidad { get; set; }
    }
}
