//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discapacidad
    {
		
		///<summary>
		///constructor de la clase
		///</summary>
        public Discapacidad()
        {
            this.Diagnostico_Discapacidad = new HashSet<Diagnostico_Discapacidad>();
            this.Discapacidad_Factor = new HashSet<Discapacidad_Factor>();
        }
    
		///<summary>
		///id de la discapacidad
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///Nombre de la discapacidad
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///descripcion de la discapacidad
		///</summary>
        public string Descripcion { get; set; }
    
		///<summary>
		///coleccion de relaciones con diagnosticos
		///</summary>
        public virtual ICollection<Diagnostico_Discapacidad> Diagnostico_Discapacidad { get; set; }
		
		///<summary>
		///coleccion de relaciones con factores
		///</summary>
        public virtual ICollection<Discapacidad_Factor> Discapacidad_Factor { get; set; }
    }
}
