//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discapacidad_Factor
    {
        public int ID { get; set; }
        public int IdDiscapacidad { get; set; }
        public int IdFactor { get; set; }
    
        public virtual Discapacidad Discapacidad { get; set; }
        public virtual Factor Factor { get; set; }
    }
}
