//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio
    {
		///<summary>
		///constructor de la clase
		///</summary>
        public Ejercicio()
        {
            this.Actividad_Ejercicio = new HashSet<Actividad_Ejercicio>();
        }
    
		///<summary>
		///ID del ejercicio
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del ejercicio
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///descripcion del ejercicio
		///</summary>
        public string Descripcion { get; set; }
    
		///<summary>
		///coleccion de relaciones con actividades
		///</summary>
        public virtual ICollection<Actividad_Ejercicio> Actividad_Ejercicio { get; set; }
    }
}
