//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
		///<summary>
		///constructor de la clase 
		///</summary>
        public Factor()
        {
            this.Discapacidad_Factor = new HashSet<Discapacidad_Factor>();
        }
    
		///<summary>
		///id del factor
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del factor
		///</summary>
        public string Nombre { get; set; }
    
		///<summary>
		///coleccion de relaciones con discapacidades
		///</summary>
        public virtual ICollection<Discapacidad_Factor> Discapacidad_Factor { get; set; }
    }
}
