//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.Discapacidad_Factor = new HashSet<Discapacidad_Factor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Discapacidad_Factor> Discapacidad_Factor { get; set; }
    }
}
