//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
		///<summary>
		///constructor de la clase
		///</summary>
        public Grupo()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Grupo_Alumno = new HashSet<Grupo_Alumno>();
            this.Maestro_Grupo = new HashSet<Maestro_Grupo>();
        }
		
		///<summary>
		///id del grupo
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del grupo
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///capacidad del grupo
		///</summary>
        public int Capacidad { get; set; }
		
		///<summary>
		///id del horario del grupo
		///</summary>
        public Nullable<int> IdHorario { get; set; }
		
		///<summary>
		///id del maestro del grupo
		///</summary>
        public Nullable<int> IdMaestro { get; set; }
    
		///<summary>
		///coleccion de alumnos en el grupo
		///</summary>
        public virtual ICollection<Alumno> Alumno { get; set; }
		
		///<summary>
		///coleccion de relaciones de alumnos en el grupo
		///</summary>
        public virtual ICollection<Grupo_Alumno> Grupo_Alumno { get; set; }
		
		///<summary>
		///horario del grupo
		///</summary>
        public virtual Horario Horario { get; set; }
		
		///<summary>
		///maestro del grupo
		///</summary>
        public virtual Maestro Maestro { get; set; }
		
		///<summary>
		///coleccion de relaciones con maestros de un grupo
		///</summary>
        public virtual ICollection<Maestro_Grupo> Maestro_Grupo { get; set; }
    }
}
