//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Rutina = new HashSet<Rutina>();
            this.Rutina1 = new HashSet<Rutina>();
        }
    
        public int ID { get; set; }
        public string Dias { get; set; }
        public string Horas { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Rutina> Rutina { get; set; }
        public virtual ICollection<Rutina> Rutina1 { get; set; }
    }
}
