//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
		///<summary>
		///constructor de la clase
		///</summary>
        public Horario()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Rutina = new HashSet<Rutina>();
            this.Rutina1 = new HashSet<Rutina>();
        }
		
		///<summary>
		///id del horario
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///dias del horario
		///</summary>
        public string Dias { get; set; }
		
		///<summary>
		///horas del horario
		///</summary>
        public string Horas { get; set; }
		
		///<summary>
		///string representando los dias y las horas del horario
		///</summary>
        public string ToString 
        { get
            {
                return Dias + "---" + Horas;
            }
        }
		
		///<summary>
		///coleccion de grupos con el mismo horario
		///</summary>
        public virtual ICollection<Grupo> Grupo { get; set; }
		
		///<summary>
		///coleccion con rutinas en el mismo horario
		///</summary>
        public virtual ICollection<Rutina> Rutina { get; set; }
        public virtual ICollection<Rutina> Rutina1 { get; set; }
    }
}
