//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_Grupo
    {
		///<summary>
		///id de la relacion
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///id del maestro
		///</summary>
        public int IdMaestro { get; set; }
		
		///<summary>
		///id del grupo
		///</summary>
        public int IdGrupo { get; set; }
    
		///<summary>
		///grupo de la relacion
		///</summary>
        public virtual Grupo Grupo { get; set; }
		
		///<summary>
		///maestro de la relacion
		///</summary>
        public virtual Maestro Maestro { get; set; }
    }
}
