//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_Grupo
    {
        public int ID { get; set; }
        public int IdMaestro { get; set; }
        public int IdGrupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
