//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
	
		///<summary>
		///constructor de la clase 
		///</summary>
        public Maestro()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Maestro_Grupo = new HashSet<Maestro_Grupo>();
        }
		
		///<summary>
		///id del maestro
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del maestro
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///direccion del maestro
		///</summary>
        public string Direccion { get; set; }
		
		///<summary>
		///email del maestro
		///</summary>
        public string Email { get; set; }
		
		///<summary>
		///telefono del maestro
		///</summary>
        public string Telefono { get; set; }
		
		///<summary>
		///celular del maestro
		///</summary>
        public string Celular { get; set; }
		
		///<summary>
		///RFC del maestro
		///</summary>
        public string Rfc { get; set; }
		
		///<summary>
		///fecha de ingreso a la institucion
		///</summary>
        public System.DateTime FechaIngreso { get; set; }
    
		///<summary>
		///coleccion de grupos que el maestro asesora
		///</summary>
        public virtual ICollection<Grupo> Grupo { get; set; }
		
		///<summary>
		///coleccion de relaciones 
		///</summary>
        public virtual ICollection<Maestro_Grupo> Maestro_Grupo { get; set; }
    }
}
