//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
	
		///<summary>
		///constructor de la clase 
		///</summary>
        public Medicamento()
        {
            this.Alumno_Medicamento = new HashSet<Alumno_Medicamento>();
        }
    
		///<summary>
		///id del medicamento
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del medicamento
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///descripcion del medicamento
		///</summary>
        public string Descripcion { get; set; }
		
		///<summary>
		///horas del medicamento
		///</summary>
        public string Horas { get; set; }
		
		///<summary>
		///coleccion de relaciones 
		///</summary>
        public virtual ICollection<Alumno_Medicamento> Alumno_Medicamento { get; set; }
    }
}
