//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
	
		///<summary>
		///constructor de la clase 
		///</summary>
        public Entidades()
            : base("name=Entidades")
        {
        }
		
		
		///<summary>
		///onCreating
		///</summary>
		///<param name = "modelBuilder"></param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
		///<summary>
		///coleccion de actividades
		///</summary>
        public DbSet<Actividad> Actividad { get; set; }
		
		///<summary>
		///coleccion de relaciones 
		///</summary>
        public DbSet<Actividad_Ejercicio> Actividad_Ejercicio { get; set; }
		
		///<summary>
		///coleccion de alergias
		///</summary>
        public DbSet<Alergia> Alergia { get; set; }
		
		///<summary>
		///coleccion de alumnos
		///</summary>
        public DbSet<Alumno> Alumno { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Alumno_Alergia> Alumno_Alergia { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Alumno_Medicamento> Alumno_Medicamento { get; set; }
		
		///<summary>
		///coleccion de diagnosticos
		///</summary>
        public DbSet<Diagnostico> Diagnostico { get; set; }
		
		///<summary>
		///coleccion de relaciones 
		///</summary>
        public DbSet<Diagnostico_Discapacidad> Diagnostico_Discapacidad { get; set; }
		
		///<summary>
		///coleccion de discapacidades
		///</summary>
        public DbSet<Discapacidad> Discapacidad { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Discapacidad_Factor> Discapacidad_Factor { get; set; }
		
		///<summary>
		///coleccion de ejercicios
		///</summary>
        public DbSet<Ejercicio> Ejercicio { get; set; }
		
		///<summary>
		///coleccion de factores
		///</summary>
        public DbSet<Factor> Factor { get; set; }
		
		///<summary>
		///coleccion de grupos
		///</summary>
        public DbSet<Grupo> Grupo { get; set; }
		
		///<summary>
		///coleccion de relaciones 
		///</summary>
        public DbSet<Grupo_Alumno> Grupo_Alumno { get; set; }
		
		///<summary>
		///coleccion de horarios
		///</summary>
        public DbSet<Horario> Horario { get; set; }
		
		///<summary>
		///coleccion de maestros
		///</summary>
        public DbSet<Maestro> Maestro { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Maestro_Grupo> Maestro_Grupo { get; set; }
		
		///<summary>
		///coleccion de medicamentos 
		///</summary>
        public DbSet<Medicamento> Medicamento { get; set; }
		
		///<summary>
		///coleccion de programas
		///</summary>
        public DbSet<Programa> Programa { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Programa_Actividad> Programa_Actividad { get; set; }
		
		///<summary>
		///coleccion de rutinas 
		///</summary>
        public DbSet<Rutina> Rutina { get; set; }
		
		///<summary>
		///coleccion de relaciones
		///</summary>
        public DbSet<Rutina_Programa> Rutina_Programa { get; set; }
		
		///<summary>
		///coleccion de tutores
		///</summary>
        public DbSet<Tutor> Tutor { get; set; }
		
		///<summary>
		///coleccion de usuarios
		///</summary>
        public DbSet<Usuario> Usuario { get; set; }
    }
}
