//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutina
    {
	
		///<summary>
		///constructor de la clase
		///</summary>
        public Rutina()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Rutina_Programa = new HashSet<Rutina_Programa>();
        }
    
		///<summary>
		///id de la rutina
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre de la rutina
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///id del maestro que imparte la rutina
		///</summary>
        public Nullable<int> IdMaestro { get; set; }
		
		///<summary>
		///lugar de la rutina
		///</summary>
        public string Lugar { get; set; }
		
		///<summary>
		///finalidad de la rutina
		///</summary>
        public string Finalidad { get; set; }
		
		///<summary>
		///id del horario
		///</summary>
        public Nullable<int> IdHorario { get; set; }
    
		///<summary>
		///coleccion de alumnos en la rutina
		///</summary>
        public virtual ICollection<Alumno> Alumno { get; set; }
		
		///<summary>
		///horario de la rutina
		///</summary>
        public virtual Horario Horario { get; set; }
        public virtual Horario Horario1 { get; set; }
		
		///<summary>
		///coleccion de relaciones con programas
		///</summary>
        public virtual ICollection<Rutina_Programa> Rutina_Programa { get; set; }
    }
}
