//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
		///<summary>
		///constructor de la clase 
		///</summary>
        public Tutor()
        {
            this.Alumno = new HashSet<Alumno>();
        }
    
		///<summary>
		///id del tutor
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del tutor
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///direccion del tutor
		///</summary>
        public string Direccion { get; set; }
		
		///<summary>
		///telefono del tutor
		///</summary>
        public string Telefono { get; set; }
		
		///<summary>
		///celular del tutor
		///</summary>
        public string Celular { get; set; }
    
		///<summary>
		///coleccion de alumnos del tutor
		///</summary>
        public virtual ICollection<Alumno> Alumno { get; set; }
    }
}
