//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
		///<summary>
		///id del usuario
		///</summary>
        public int ID { get; set; }
		
		///<summary>
		///nombre del usuario
		///</summary>
        public string Nombre { get; set; }
		
		///<summary>
		///direccion del usuario
		///</summary>
        public string Direccion { get; set; }
		///<summary>
		///telefono del usuario
		///</summary>
        public string Telefono { get; set; }
		
		///<summary>
		///email del usuario
		///</summary>
        public string Email { get; set; }
		
		///<summary>
		///celular del usuario
		///</summary>
        public string Celular { get; set; }
		
		///<summary>
		///permisos del usuario
		///</summary>
        public int Permisos { get; set; }
		
		///<summary>
		///nombre de inicio de sesion
		///</summary>
        public string UserName { get; set; }
		
		///<summary>
		///clave de inicio de sesion
		///</summary>
        public string Contrasenha { get; set; }
    }
}
