//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.Alumno_Alergia = new HashSet<Alumno_Alergia>();
            this.Alumno_Medicamento = new HashSet<Alumno_Medicamento>();
            this.Grupo_Alumno = new HashSet<Grupo_Alumno>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int IdTutor { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string CURP { get; set; }
        public string GradoAcademico { get; set; }
        public string TallaUniforme { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdRutina { get; set; }
    
        public virtual ICollection<Alumno_Alergia> Alumno_Alergia { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Rutina Rutina { get; set; }
        public virtual ICollection<Alumno_Medicamento> Alumno_Medicamento { get; set; }
        public virtual ICollection<Grupo_Alumno> Grupo_Alumno { get; set; }
    }
}
