//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Came.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Grupo_Alumno = new HashSet<Grupo_Alumno>();
            this.Maestro_Grupo = new HashSet<Maestro_Grupo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Capacidad { get; set; }
        public Nullable<int> IdHorario { get; set; }
        public Nullable<int> IdMaestro { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Grupo_Alumno> Grupo_Alumno { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Maestro Maestro { get; set; }
        public virtual ICollection<Maestro_Grupo> Maestro_Grupo { get; set; }
    }
}
